<?xml version="1.0"?>

<robot name="diff_robot" xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include filename="$(find diff_robot)/urdf/rviz_stuff.xacro"/>
  <xacro:include filename="$(find diff_robot)/urdf/gazebo_stuff.xacro"/>
  <xacro:property name="chassis_length" value="1.0"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.10"/>
  <xacro:property name="wheel_radius" value="0.20"/>
  <xacro:property name="wheel_thickness" value="0.10"/>
  <xacro:property name="wheel_joint_offset" value="0.05"/>
  <xacro:property name="caster_radius" value="${wheel_radius - chassis_height/2 -0.05}"/>

  <xacro:macro name="chassis_inertia">
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.04209" ixy="0" ixz="0" iyy="0.01084" iyz="0" izz="0.052084"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel_inertia">
    <inertial>
      <mass value="0.20"/>
      <inertia ixx="0.0023" ixy="0" ixz="0" iyy="0.0023" iyz="0" izz="0.004"/>
    </inertial>
  </xacro:macro>

  <!-- Main Body-->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="white"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:chassis_inertia />
    <visual name="caster">
      <origin xyz="${chassis_length/4} 0 -${chassis_height/2 +0.05}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </visual>
    <collision name="caster_collision">
      <origin xyz="${chassis_length/4} 0 -${chassis_height/2 +0.05}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
  </link>

  <!--Right Wheel-->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="green"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:wheel_inertia />
  </link>

  <!--chassis Right Joint-->
  <joint name="chassis_right_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <origin xyz="-${chassis_length/4} ${chassis_width/2 + wheel_joint_offset} 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="right_wheel"/>
  </joint>

  <!--Left Wheel-->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <material name="green"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:wheel_inertia />
  </link>

  <!--chassis_left_joint-->
  <joint name="chassis_left_joint" type="continuous">
    <axis xyz="0 1 0"/>
    <origin xyz="-${chassis_length/4} -${chassis_width/2 + wheel_joint_offset} 0" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="left_wheel"/>
  </joint>

  <!--Laser link-->
  <link name="laser_scanner">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius/2}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius/2}"/>
      </geometry>
    </collision>
  </link>
  <!--Laser Joint-->
  <joint name="laser_joint" type="fixed">
    <origin xyz="${chassis_length/3} 0 ${chassis_height/2 + wheel_thickness/2}"/>
    <parent link="chassis"/>
    <child link="laser_scanner"/>
  </joint>
</robot>
